### ISSUE TITLE
Adding plugin causes errors

### ISSUE THREAD

**Issue by hwgn** [pschichtel/LyricsReloaded#18]
Whenever i add the plugin to the folder (old or updated one), upon opening MusicBee, it grants me two issues: First is a error box inside MusicBee (sorry for the german)
`MusicBee v3.1.6590.32668 (Win10.0), 20 Mai 2018 13:56:

```
System.NullReferenceException: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
   bei CubeIsland.LyricsReloaded.LyricsReloaded.shutdown()
   bei CubeIsland.LyricsReloaded.LyricsReloaded.Finalize()
```

Additionally, i get a normal windows popup stating:
```
An error occurred during plugin startup: The process can't access the file "C:\...\Appdata\Roaming\MusicBee\mb_LyricsReloaded.log" because it's used by another process.
```

Closing both errors exits the program.

The log (the file referred to above) spits this out:
>20.05.2018 02:02:10 [INFO] mb_LyricsReloaded in version 1.1.2.0 started!
20.05.2018 02:02:10 [DEBUG] Loading config from field provider_azlyrics_com
20.05.2018 02:02:10 [INFO] Provider loaded: A-Z Lyrics Universe
20.05.2018 02:02:10 [DEBUG] Loading config from field provider_cuspajz_com
20.05.2018 02:02:10 [INFO] Provider loaded: Cušpajz
20.05.2018 02:02:10 [DEBUG] Loading config from field provider_hindilyrics_net
20.05.2018 02:02:10 [INFO] Provider loaded: Hindi Lyrics
20.05.2018 02:02:10 [DEBUG] Loading config from field provider_letras_mus_br
20.05.2018 02:02:10 [INFO] Provider loaded: Letras de músicas
20.05.2018 02:02:10 [DEBUG] Loading config from field provider_lyrics_wikia_com
20.05.2018 02:02:10 [INFO] Provider loaded: LyricWiki
20.05.2018 02:02:10 [DEBUG] Loading config from field provider_lyrics_wikia_com_gn
20.05.2018 02:02:10 [INFO] Provider loaded: LyricWiki Gracenote
20.05.2018 02:02:10 [DEBUG] Loading config from field provider_metrolyrics_com
20.05.2018 02:02:10 [INFO] Provider loaded: MetroLyrics
20.05.2018 02:02:10 [DEBUG] Loading config from field provider_oldielyrics_com
20.05.2018 02:02:10 [INFO] Provider loaded: Oldies Lyrics
20.05.2018 02:02:10 [DEBUG] Loading config from field provider_pinkradio_com
20.05.2018 02:02:10 [INFO] Provider loaded: Pink Radio
20.05.2018 02:02:10 [DEBUG] Loading config from field provider_rapgenius_com
20.05.2018 02:02:10 [INFO] Provider loaded: Rap Genius
20.05.2018 02:02:10 [DEBUG] Loading config from field provider_smriti_com
20.05.2018 02:02:10 [INFO] Provider loaded: Smriti
20.05.2018 02:02:10 [DEBUG] Loading config from field provider_songlyrics_com
20.05.2018 02:02:10 [INFO] Provider loaded: Song Lyrics
20.05.2018 02:02:10 [DEBUG] Loading config from field provider_tekstowo_pl
20.05.2018 02:02:10 [INFO] Provider loaded: Tekstowo
20.05.2018 02:02:10 [DEBUG] Loading config from field provider_teksty_org
20.05.2018 02:02:10 [INFO] Provider loaded: Teksty
20.05.2018 02:02:10 [DEBUG] Loading config from field provider_urbanlyrics_com
20.05.2018 02:02:10 [INFO] Provider loaded: Urban Lyrics
20.05.2018 02:02:10 [DEBUG] Received a notification of type PluginStartup
20.05.2018 02:02:10 [DEBUG] gzip compression detected

Could it be that "gzip compression" refers to a faulty extraction or the like?

**Comment by pschichtel** [comment]
Please refer to the fork from @mbfrankz: https://github.com/mbfrankz/LyricsReloaded
